global:
  scrape_interval:     5s
  scrape_timeout:     2s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitoring-stack'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - ./alert.rules
  - "rules/alert.yml"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'netdata'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus_all_hosts ]
    honor_labels: true
    static_configs:
      - targets: ['netdata:19999']

  - job_name: 'healthchecks-mauricenash1gmailcom'
    scheme: https
    metrics_path: /projects/8eeea913-83fc-4b52-99f9-55e1a3b9d33d/metrics/ZjXGELuU8zHCwfIzVUfmXL9CP4LF3qNf
    static_configs:
    - targets: ['healthchecks.io']

  - job_name: 'blackbox-http(s)'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
    - targets:
      - localhost:9090
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: jumpbox:9090
  
  - job_name: 'speedtest'
    metrics_path: /metrics
    scrape_interval: 5m
    scrape_timeout: 60s # running speedtest needs time to complete
    honor_labels: true
    static_configs:
      - targets: ['speedtest:9798']
  
  - job_name: 'influxdb'
    scrape_interval: 5s
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'ping'
    metrics_path: /probe
    scrape_interval: 15s
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - pinghosts.yaml
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #first is the url, thus unique for instance
        target_label: instance
        replacement: $1
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #second is humanname to use in charts
        target_label: humanname
        replacement: $2
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #third state whether this is testing external or internal network
        target_label: routing
        replacement: $3
      - source_labels: [__address__]
        regex: '(.*);(.*);(.*);(.*)'  #fourth is which switch/router the device is connected to.
        target_label: switching
        replacement: $4
      - source_labels: [instance]
        target_label: __param_target
      - target_label: __address__
        replacement: ping:9115  # The blackbox exporter's real hostname:port.

  # - job_name: watchtower
  #   scrape_interval: 5s
  #   metrics_path: /v1/metrics
  #   bearer_token: demotoken
  #   static_configs:
  #     - targets: [':8080']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
